\encoding UTF8;
\i tables/balance_sheet.sql;
\i tables/cache.sql;
\i tables/cashflow_statement.sql;
\i tables/history_1d.sql;
\i tables/history_instruments.sql;
\i tables/income_statement.sql;
\i tables/industries.sql;
\i tables/industry_constituents.sql;
\i tables/instrumentinfos.sql;
\i tables/power.sql;
\i tables/trading_derivative_indicator.sql;

\i functions/at.sql
\i functions/ca.sql
\i functions/ca10.sql
\i functions/ca120.sql
\i functions/ca20.sql
\i functions/ca250.sql
\i functions/ca5.sql
\i functions/ca60.sql
\i functions/cacher.sql
\i functions/cachew.sql
\i functions/can.sql
\i functions/cr.sql
\i functions/dar.sql
\i functions/dma.sql
\i functions/em.sql
\i functions/er.sql
\i functions/finance.sql
\i functions/hod.sql
\i functions/lod.sql
\i functions/ltlr.sql
\i functions/mcst.sql
\i functions/npm.sql
\i functions/p10.sql
\i functions/p120.sql
\i functions/p20.sql
\i functions/p250.sql
\i functions/p5.sql
\i functions/p60.sql
\i functions/pe.sql
\i functions/plforecast.sql
\i functions/pow.sql
\i functions/qr.sql
\i functions/rate.sql
\i functions/rate10.sql
\i functions/rate120.sql
\i functions/rate20.sql
\i functions/rate250.sql
\i functions/rate5.sql
\i functions/rate60.sql
\i functions/ratelod10.sql
\i functions/ratelod120.sql
\i functions/ratelod20.sql
\i functions/ratelod250.sql
\i functions/ratelod5.sql
\i functions/ratelod60.sql
\i functions/ratelodn.sql
\i functions/raten.sql
\i functions/roe.sql
\i functions/rpa.sql
\i functions/rpd.sql
\i functions/s10.sql
\i functions/s120.sql
\i functions/s20.sql
\i functions/s250.sql
\i functions/s5.sql
\i functions/s60.sql
\i functions/sv10.sql
\i functions/sv120.sql
\i functions/sv20.sql
\i functions/sv250.sql
\i functions/sv5.sql
\i functions/sv60.sql
\i functions/toprange.sql
\i functions/ts.sql
\i functions/wcr.sql
